In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"c:\Users\Admin\Desktop\Visualization\Final\dseb63_installments_payments.csv")

In [3]:
print("Kích thước dữ liệu:", df.shape)
df.info()
df.head()

Kích thước dữ liệu: (7744758, 8)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7744758 entries, 0 to 7744757
Data columns (total 8 columns):
 #   Column                  Dtype  
---  ------                  -----  
 0   SK_ID_PREV              int64  
 1   NUM_INSTALMENT_VERSION  float64
 2   NUM_INSTALMENT_NUMBER   int64  
 3   DAYS_INSTALMENT         float64
 4   DAYS_ENTRY_PAYMENT      float64
 5   AMT_INSTALMENT          float64
 6   AMT_PAYMENT             float64
 7   SK_ID_CURR              float64
dtypes: float64(6), int64(2)
memory usage: 472.7 MB


SK_ID_PREV  NUM_INSTALMENT_VERSION  NUM_INSTALMENT_NUMBER  DAYS_INSTALMENT  \
0     1054186                     1.0                      6          -1180.0   
1     2452854                     1.0                     21           -546.0   
2     1054186                     1.0                      2          -1300.0   
3     1682318                     1.0                      2           -240.0   
4     2452854                     1.0                     10           -876.0   

   DAYS_ENTRY_PAYMENT  AMT_INSTALMENT  AMT_PAYMENT  SK_ID_CURR  
0             -1187.0        6948.360     6948.360    147397.0  
1              -552.0       11302.605    11302.605    147397.0  
2             -1307.0        6948.360     6948.360    147397.0  
3              -243.0        7374.510     7374.510    147397.0  
4              -882.0       11302.605    11302.605    147397.0

In [4]:

missing_values = df.isnull().sum()
missing_percentage = (missing_values / len(df)) * 100
missing_data = pd.DataFrame({'Số lượng thiếu': missing_values, 'Tỷ lệ thiếu (%)': missing_percentage})
missing_data = missing_data[missing_data['Số lượng thiếu'] > 0].sort_values(by='Tỷ lệ thiếu (%)', ascending=False)

print("\nCác cột có giá trị thiếu:")
print(missing_data)



Các cột có giá trị thiếu:
                    Số lượng thiếu  Tỷ lệ thiếu (%)
DAYS_ENTRY_PAYMENT            1639         0.021163
AMT_PAYMENT                   1639         0.021163
AMT_INSTALMENT                   1         0.000013
SK_ID_CURR                       1         0.000013


In [5]:
df['SK_ID_PREV'][df['AMT_PAYMENT'].isna()].unique()

array([2745338, 1724459, 1376802, 1007398, 1812248, 1682768, 1369365,
       1207737, 1472146, 1856378, 1430471, 2556314, 2726364, 2791456,
       2071031, 2787902, 2287929, 1113429, 1871097, 1084808, 1994613,
       1289505, 2221606, 1249737, 2552537, 2335193, 2362820, 1667997,
       1469336, 1847900, 1894206, 1413302, 1179358, 2312379, 2062917,
       1531600, 1147405, 1444457, 1479246, 2205844, 1519688, 2137320,
       1470301, 1523053, 2552221, 2366689, 1947105, 1816234, 1776396,
       2353633, 1872044, 1685275, 2248491, 1642077, 1155260, 1723848,
       2313094, 1692360, 2707042, 1811097, 2132734, 1780042, 2776343,
       1290531, 2199734, 1770464, 2161734, 1152346, 2636131, 1251800,
       1105558, 1057554, 2630937, 2110919, 1946855, 2510034, 1081756,
       2039159, 1660621, 2394847, 2482765, 2397029, 1198509, 1930738,
       2476396, 2092519, 1923738, 2668563, 2247677, 2074104, 1550834,
       2056812, 1046076, 2737378, 2740842, 2475981, 1641221, 2077541,
       1444536, 1977

2 cột DAYS_ENTRY_PAYMENT và AMT_PAYMENT có các giá trị nan luôn đi đôi với nhau 

In [7]:
df[(df['DAYS_ENTRY_PAYMENT'].isna()) & (df['AMT_PAYMENT'].isna())]

SK_ID_PREV  NUM_INSTALMENT_VERSION  NUM_INSTALMENT_NUMBER  \
20968       2745338                     0.0                     49   
20969       2745338                     0.0                     48   
20970       2745338                     0.0                     50   
23789       1724459                     1.0                     11   
30552       1376802                     0.0                      2   
...             ...                     ...                    ...   
7743511     1088123                     0.0                     68   
7743512     1088123                     0.0                     70   
7743514     1088123                     0.0                     69   
7743516     1088123                     0.0                     71   
7744757     2657771                     0.0                     94   

         DAYS_INSTALMENT  DAYS_ENTRY_PAYMENT  AMT_INSTALMENT  AMT_PAYMENT  \
20968             -992.0                 NaN            67.5          NaN   
20969            -1023.0                 NaN            67.5          NaN   
20970             -963.0                 NaN            67.5          NaN   
23789               -3.0                 NaN         43839.0          NaN   
30552             -733.0                 NaN             0.0          NaN   
...                  ...                 ...             ...          ...   
7743511          -1727.0                 NaN            67.5          NaN   
7743512          -1668.0                 NaN            67.5          NaN   
7743514          -1699.0                 NaN            67.5          NaN   
7743516          -1638.0                 NaN            67.5          NaN   
7744757             -4.0                 NaN             NaN          NaN   

         SK_ID_CURR  
20968      280024.0  
20969      280024.0  
20970      280024.0  
23789      135730.0  
30552      239362.0  
...             ...  
7743511     98758.0  
7743512     98758.0  
7743514     98758.0  
7743516     98758.0  
7744757         NaN  

[1639 rows x 8 columns]

Tạo một bảng con của các id_prev có thông tin bị nan


In [8]:
sk_id_prev_null = df['SK_ID_PREV'][(df['AMT_PAYMENT'].isna())].unique()

In [9]:
sk_id_prev_null

array([2745338, 1724459, 1376802, 1007398, 1812248, 1682768, 1369365,
       1207737, 1472146, 1856378, 1430471, 2556314, 2726364, 2791456,
       2071031, 2787902, 2287929, 1113429, 1871097, 1084808, 1994613,
       1289505, 2221606, 1249737, 2552537, 2335193, 2362820, 1667997,
       1469336, 1847900, 1894206, 1413302, 1179358, 2312379, 2062917,
       1531600, 1147405, 1444457, 1479246, 2205844, 1519688, 2137320,
       1470301, 1523053, 2552221, 2366689, 1947105, 1816234, 1776396,
       2353633, 1872044, 1685275, 2248491, 1642077, 1155260, 1723848,
       2313094, 1692360, 2707042, 1811097, 2132734, 1780042, 2776343,
       1290531, 2199734, 1770464, 2161734, 1152346, 2636131, 1251800,
       1105558, 1057554, 2630937, 2110919, 1946855, 2510034, 1081756,
       2039159, 1660621, 2394847, 2482765, 2397029, 1198509, 1930738,
       2476396, 2092519, 1923738, 2668563, 2247677, 2074104, 1550834,
       2056812, 1046076, 2737378, 2740842, 2475981, 1641221, 2077541,
       1444536, 1977

In [10]:
df_filtered = df[df['SK_ID_PREV'].isin(sk_id_prev_null)]

In [11]:
df_filtered.shape

(27940, 8)

In [12]:
df_filtered = df_filtered.sort_values(by=['SK_ID_PREV', 'NUM_INSTALMENT_NUMBER'])
null_entries = df_filtered[(df_filtered['DAYS_ENTRY_PAYMENT'].isna())&(df_filtered['AMT_PAYMENT'].isna())]

In [13]:
null_entries

SK_ID_PREV  NUM_INSTALMENT_VERSION  NUM_INSTALMENT_NUMBER  \
2622876     1001758                     0.0                     24   
2622873     1001758                     0.0                     25   
2622874     1001758                     0.0                     26   
2622872     1001758                     0.0                     27   
6455805     1004174                     2.0                    101   
...             ...                     ...                    ...   
6878190     2841275                     0.0                     45   
6878187     2841275                     0.0                     46   
6878189     2841275                     0.0                     47   
1905692     2841786                     0.0                     67   
1905693     2841786                     0.0                     68   

         DAYS_INSTALMENT  DAYS_ENTRY_PAYMENT  AMT_INSTALMENT  AMT_PAYMENT  \
2622876          -1915.0                 NaN          96.435          NaN   
2622873          -1884.0                 NaN          67.500          NaN   
2622874          -1853.0                 NaN          67.500          NaN   
2622872          -1825.0                 NaN          67.500          NaN   
6455805          -2387.0                 NaN        1350.000          NaN   
...                  ...                 ...             ...          ...   
6878190          -1929.0                 NaN          67.500          NaN   
6878187          -1898.0                 NaN          67.500          NaN   
6878189          -1867.0                 NaN          67.500          NaN   
1905692           -996.0                 NaN          67.500          NaN   
1905693           -966.0                 NaN          67.500          NaN   

         SK_ID_CURR  
2622876    191320.0  
2622873    191320.0  
2622874    191320.0  
2622872    191320.0  
6455805     67444.0  
...             ...  
6878190     81627.0  
6878187     81627.0  
6878189     81627.0  
1905692    267146.0  
1905693    267146.0  

[1639 rows x 8 columns]

Tạo hàm tính tổng số tiền đã trả trong mỗi kỳ thanh toán

In [ ]:

def calculate_total_payment(group):
    total = 0
    total_list = []
    for _, row in group.iterrows():
        # Số tiền thanh toán trong khoảng hiện tại
        payment = row['AMT_PAYMENT']
        
        # Nếu tổng vượt AMT_INSTALMENT, chỉ lấy AMT_INSTALMENT
        if total + payment > row['AMT_INSTALMENT']:
            total = row['AMT_INSTALMENT']
        else:
            total += payment
        
        total_list.append(total)
    group['TOTAL_AMT_PAYMENT'] = total_list
    return group






In [15]:
df_filtered = df_filtered.groupby(['SK_ID_PREV', 'NUM_INSTALMENT_NUMBER']).apply(calculate_total_payment)

# Kiểm tra kết quả
df_filtered

C:\Users\Admin\AppData\Local\Temp\ipykernel_27472\3563408711.py:1: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use 

	>>> .groupby(..., group_keys=True)
  df_filtered = df_filtered.groupby(['SK_ID_PREV', 'NUM_INSTALMENT_NUMBER']).apply(calculate_total_payment)


SK_ID_PREV  NUM_INSTALMENT_VERSION  NUM_INSTALMENT_NUMBER  \
2622867     1001758                     0.0                      1   
2622844     1001758                     0.0                      2   
2622864     1001758                     0.0                      3   
2622858     1001758                     0.0                      4   
2622857     1001758                     0.0                      5   
...             ...                     ...                    ...   
1905664     2841786                     0.0                     64   
1905628     2841786                     0.0                     65   
1905663     2841786                     0.0                     66   
1905692     2841786                     0.0                     67   
1905693     2841786                     0.0                     68   

         DAYS_INSTALMENT  DAYS_ENTRY_PAYMENT  AMT_INSTALMENT  AMT_PAYMENT  \
2622867          -2619.0             -2619.0        1890.000     1890.000   
2622844          -2584.0             -2586.0        1890.000     1890.000   
2622864          -2555.0             -2552.0        1890.000     1890.000   
2622858          -2524.0             -2510.0        1890.000     1890.000   
2622857          -2494.0             -2495.0        1890.000     1890.000   
...                  ...                 ...             ...          ...   
1905664          -1056.0             -1068.0          67.500       63.675   
1905628          -1068.0             -1068.0           3.825        3.825   
1905663          -1027.0             -1055.0          67.500        3.825   
1905692           -996.0                 NaN          67.500          NaN   
1905693           -966.0                 NaN          67.500          NaN   

         SK_ID_CURR  TOTAL_AMT_PAYMENT  
2622867    191320.0           1890.000  
2622844    191320.0           1890.000  
2622864    191320.0           1890.000  
2622858    191320.0           1890.000  
2622857    191320.0           1890.000  
...             ...                ...  
1905664    267146.0             67.500  
1905628    267146.0              3.825  
1905663    267146.0              3.825  
1905692    267146.0                NaN  
1905693    267146.0                NaN  

[27940 rows x 9 columns]

Xử lý trường hợp số tiền phải trả = 0 (AMT_INSTALL = 0)


In [16]:
df_filtered['SK_ID_PREV'][df_filtered['AMT_INSTALMENT'] == 0].unique()

array([1131442, 1302284, 1376802, 1384283, 1948792, 2028865, 2204278,
       2287929, 2292865, 2458481, 2495415, 2563080, 2596990, 2792386,
       2820929], dtype=int64)

In [17]:
# Bước 1: Lấy danh sách SK_ID_PREV từ điều kiện AMT_INSTALMENT == 0
selected_ids = df_filtered['SK_ID_PREV'][df_filtered['AMT_INSTALMENT'] == 0].unique()

# Bước 2: Xử lý từng trường hợp
for sk_id in selected_ids:
    # Lọc các hàng theo SK_ID_PREV
    sub_df = df_filtered[df_filtered['SK_ID_PREV'] == sk_id]
    
    # Trường hợp 1: Nếu có NUM_INSTALMENT_NUMBER = 1 và chứa NaN
    if (sub_df['NUM_INSTALMENT_NUMBER'] == 1).any() and sub_df[['AMT_PAYMENT', 'DAYS_ENTRY_PAYMENT']].isna().any().any():
        # Xóa các hàng chứa NaN
        df_filtered = df_filtered.drop(
            sub_df[(sub_df['NUM_INSTALMENT_NUMBER'] == 1) & (sub_df[['AMT_PAYMENT', 'DAYS_ENTRY_PAYMENT']].isna().any(axis=1))].index
        )
        
    else:
        # Trường hợp 2: Fill giá trị NaN bằng giá trị ngay trước nó
        sub_df = sub_df.fillna(method='ffill')

        # Cập nhật lại vào bảng gốc
        df_filtered.update(sub_df)


Xử lý trường hợp trả quá sớm ( < 1 tháng)

In [18]:
df_filtered['SK_ID_PREV'][(df_filtered['DAYS_INSTALMENT'] > -30)].unique()

array([1009475., 1010608., 1016839., 1026856., 1030134., 1040056.,
       1042009., 1046076., 1050330., 1055818., 1057554., 1058599.,
       1061852., 1062110., 1075308., 1080529., 1100277., 1103554.,
       1106809., 1108021., 1109046., 1110185., 1112197., 1112327.,
       1131442., 1132341., 1143584., 1147405., 1160459., 1164023.,
       1173472., 1176728., 1182516., 1183254., 1187109., 1187361.,
       1189302., 1198509., 1207430., 1207806., 1207955., 1210811.,
       1213178., 1213822., 1226959., 1231943., 1232615., 1233174.,
       1235105., 1237551., 1249737., 1251800., 1251874., 1261872.,
       1262066., 1265332., 1270458., 1270812., 1281448., 1284860.,
       1284922., 1285306., 1302363., 1305319., 1310642., 1315244.,
       1319969., 1323284., 1326666., 1332653., 1335180., 1335365.,
       1339540., 1343806., 1346501., 1351298., 1351307., 1354935.,
       1368893., 1369114., 1382683., 1384283., 1385207., 1409035.,
       1410561., 1413302., 1430471., 1440026., 1463062., 14639

In [19]:
# Bước 1: Lọc ra các SK_ID_PREV với điều kiện DAYS_INSTALMENT > -30
selected_ids = df_filtered['SK_ID_PREV'][(df_filtered['DAYS_INSTALMENT'] > -30)].unique()

# Bước 2: Lọc ra các hàng KHÔNG thuộc các SK_ID_PREV được tìm thấy hoặc không chứa giá trị NaN
df_filtered = df_filtered[~((df_filtered['SK_ID_PREV'].isin(selected_ids)) & 
                            (df_filtered['AMT_PAYMENT'].isna() | df_filtered['DAYS_ENTRY_PAYMENT'].isna()))]


In [20]:
df_filtered['SK_ID_PREV'][(df_filtered['DAYS_INSTALMENT'] > -30)].unique()

array([1026856., 1046076., 1112197., 1131442., 1207430., 1235105.,
       1262066., 1326666., 1332653., 1384283., 1463952., 1472477.,
       1508036., 1698596., 1731324., 1738818., 1821892., 1829968.,
       1856378., 1873929., 1894206., 1906196., 2028865., 2044612.,
       2055767., 2075288., 2163183., 2208529., 2256773., 2260699.,
       2287929., 2292046., 2413658., 2418198., 2426902., 2510034.,
       2609604., 2622062., 2675491., 2726364., 2761986., 2792386.,
       2820929., 2823256.])

In [21]:
df_filtered.shape

(27288, 9)

Xử lý trường hợp trả đủ nhưng do chia thành nhiều lần trả nên có giá trị nan

In [22]:
# Bước 1: Tìm các hàng có giá trị NaN trong AMT_PAYMENT
nan_condition = df_filtered['AMT_PAYMENT'].isna()

# Bước 2: Dịch dữ liệu xuống 1 hàng để kiểm tra điều kiện của hàng ngay trước
shifted_amt_install = df_filtered['AMT_INSTALMENT'].shift(1)
shifted_amt_payment = df_filtered['AMT_PAYMENT'].shift(1)
shifted_total_amt_payment = df_filtered['TOTAL_AMT_PAYMENT'].shift(1)
shifted_sk_id_prev = df_filtered['SK_ID_PREV'].shift(1)

# Bước 3: Kiểm tra điều kiện cho hàng ngay trước
valid_prev_condition = (
    (shifted_amt_install < shifted_amt_payment) & 
    (shifted_amt_install == shifted_total_amt_payment) &
    (shifted_sk_id_prev == df_filtered['SK_ID_PREV'])  # Đảm bảo cùng SK_ID_PREV
)

# Bước 4: Kết hợp điều kiện để chọn SK_ID_PREV
df_filtered.loc[nan_condition & valid_prev_condition, 'SK_ID_PREV'].unique()

array([1243892., 1290953., 1391295., 1639190., 1668535., 2215130.,
       2668563.])

In [23]:
selected_ids = df_filtered.loc[nan_condition & valid_prev_condition, 'SK_ID_PREV'].unique()

# Bước 5: Lọc và điền giá trị NaN trong các cột AMT_PAYMENT và DAYS_ENTRY_PAYMENT
df_filtered.loc[
    (df_filtered['SK_ID_PREV'].isin(selected_ids)) & (df_filtered['AMT_PAYMENT'].isna()), 
    'AMT_PAYMENT'
] = df_filtered['AMT_INSTALMENT']

df_filtered.loc[
    (df_filtered['SK_ID_PREV'].isin(selected_ids)) & (df_filtered['DAYS_ENTRY_PAYMENT'].isna()), 
    'DAYS_ENTRY_PAYMENT'
] = df_filtered['DAYS_INSTALMENT']


Xử lý trường hợp trả không đủ tiền 

In [24]:
df_filtered['SK_ID_PREV'][df_filtered['TOTAL_AMT_PAYMENT'] != df_filtered['AMT_INSTALMENT']].unique()

array([1001758., 1004174., 1004826., 1005373., 1007053., 1007055.,
       1007345., 1007398., 1016839., 1026691., 1026856., 1030134.,
       1031422., 1032257., 1033776., 1033951., 1035136., 1036148.,
       1036378., 1040056., 1046076., 1050330., 1052313., 1054261.,
       1054684., 1055818., 1057554., 1058599., 1061144., 1061852.,
       1062110., 1075308., 1081756., 1082332., 1082583., 1084808.,
       1088123., 1088442., 1092646., 1100277., 1103392., 1103554.,
       1105558., 1109046., 1110185., 1112197., 1113429., 1117009.,
       1126779., 1132341., 1147405., 1152145., 1152346., 1153254.,
       1155260., 1155853., 1156681., 1157320., 1162340., 1164023.,
       1175422., 1176728., 1176878., 1179358., 1179367., 1179719.,
       1182516., 1183254., 1184816., 1187109., 1187567., 1187619.,
       1188953., 1194457., 1195250., 1198494., 1204905., 1207430.,
       1207737., 1207806., 1210811., 1211138., 1211186., 1212390.,
       1213178., 1219801., 1223236., 1226256., 1226959., 12270

In [25]:
selected_ids = df_filtered['SK_ID_PREV'][df_filtered['TOTAL_AMT_PAYMENT'] != df_filtered['AMT_INSTALMENT']].unique()

df_filtered[((df_filtered['SK_ID_PREV'].isin(selected_ids)) & 
                            (df_filtered['AMT_PAYMENT'].isna() | df_filtered['DAYS_ENTRY_PAYMENT'].isna()))]


SK_ID_PREV  NUM_INSTALMENT_VERSION  NUM_INSTALMENT_NUMBER  \
2622876   1001758.0                     0.0                   24.0   
2622873   1001758.0                     0.0                   25.0   
2622874   1001758.0                     0.0                   26.0   
2622872   1001758.0                     0.0                   27.0   
6455805   1004174.0                     2.0                  101.0   
...             ...                     ...                    ...   
6878190   2841275.0                     0.0                   45.0   
6878187   2841275.0                     0.0                   46.0   
6878189   2841275.0                     0.0                   47.0   
1905692   2841786.0                     0.0                   67.0   
1905693   2841786.0                     0.0                   68.0   

         DAYS_INSTALMENT  DAYS_ENTRY_PAYMENT  AMT_INSTALMENT  AMT_PAYMENT  \
2622876          -1915.0                 NaN          96.435          NaN   
2622873          -1884.0                 NaN          67.500          NaN   
2622874          -1853.0                 NaN          67.500          NaN   
2622872          -1825.0                 NaN          67.500          NaN   
6455805          -2387.0                 NaN        1350.000          NaN   
...                  ...                 ...             ...          ...   
6878190          -1929.0                 NaN          67.500          NaN   
6878187          -1898.0                 NaN          67.500          NaN   
6878189          -1867.0                 NaN          67.500          NaN   
1905692           -996.0                 NaN          67.500          NaN   
1905693           -966.0                 NaN          67.500          NaN   

         SK_ID_CURR  TOTAL_AMT_PAYMENT  
2622876    191320.0                NaN  
2622873    191320.0                NaN  
2622874    191320.0                NaN  
2622872    191320.0                NaN  
6455805     67444.0                NaN  
...             ...                ...  
6878190     81627.0                NaN  
6878187     81627.0                NaN  
6878189     81627.0                NaN  
1905692    267146.0                NaN  
1905693    267146.0                NaN  

[965 rows x 9 columns]

In [26]:
selected_ids = df_filtered['SK_ID_PREV'][df_filtered['TOTAL_AMT_PAYMENT'] != df_filtered['AMT_INSTALMENT']].unique()

df_filtered = df_filtered[~((df_filtered['SK_ID_PREV'].isin(selected_ids)) & 
                            (df_filtered['AMT_PAYMENT'].isna() | df_filtered['DAYS_ENTRY_PAYMENT'].isna()))]


In [27]:
df_filtered.shape

(26323, 9)

In [28]:
df_filtered[df_filtered['AMT_PAYMENT'].isna()]

Empty DataFrame
Columns: [SK_ID_PREV, NUM_INSTALMENT_VERSION, NUM_INSTALMENT_NUMBER, DAYS_INSTALMENT, DAYS_ENTRY_PAYMENT, AMT_INSTALMENT, AMT_PAYMENT, SK_ID_CURR, TOTAL_AMT_PAYMENT]
Index: []

In [29]:
df_filtered = df_filtered.drop(columns=['TOTAL_AMT_PAYMENT'])

Update bảng con vào bảng gốc, những phần không được update là những giá trị nan đã bị xóa trong bảng con nên sẽ xóa ở bảng chính 

In [ ]:
df_filtered.index = df_filtered.index.astype(df.index.dtype) 

df.loc[df_filtered.index] = df_filtered
df.dropna(inplace=True)



In [34]:
df.isnull().sum()

SK_ID_PREV                0
NUM_INSTALMENT_VERSION    0
NUM_INSTALMENT_NUMBER     0
DAYS_INSTALMENT           0
DAYS_ENTRY_PAYMENT        0
AMT_INSTALMENT            0
AMT_PAYMENT               0
SK_ID_CURR                0
dtype: int64

In [35]:
df.shape

(7743141, 8)

In [36]:
# Thay thế giá trị trong cột AMT_INSTALMENT bằng giá trị từ cột AMT_PAYMENT nếu AMT_INSTALMENT == 0
df.loc[df['AMT_INSTALMENT'] == 0, 'AMT_INSTALMENT'] = df['AMT_PAYMENT']


In [ ]:
# Xóa những hàng nếu số tiền phải trả và số tiền thực tế trả đều = 0 (vì không có ý nghĩa gì)
df = df.drop(df[(df['AMT_PAYMENT'] == 0) & (df['AMT_INSTALMENT'] == 0)].index)


In [ ]:
df.to_csv(r'C:\Users\Admin\Desktop\Final data prep\cleaned_data\installment_payment.csv')